### ISSUE TITLE
Cannot Added Search Music to My Collection

### ISSUE THREAD

**Issue by Mikebarson** [AurousGroup/Bug-Tracker#6]
When I searched the music I found I could not add it to My Collections.

**Comment by menotim** [comment]
Same problem here.

**Comment by elchinot7** [comment]
Same problem here!

**Comment by rijulsaxena** [comment]
Here too!

**Comment by rijulsaxena** [comment]
This was already addressed in #13 
Try adding a Music Folder older in the Settings>Advanced Tab

@Mikebarson @menotim @elchinot7

**Comment by elchinot7** [comment]
I see, thanks!
@rijulsaxena

**Comment by Mikebarson** [comment]
Still does not work for me though...I've already added some music but still does not work
Keep me updated though for updates for this fix.
@rijulsaxena
